# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Tramites', 'Tramites'), ('Info', 'Info'), ('Exp', 'Exp')], max_length=256, null=True),
        ),
    ]
