# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 03:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170506_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infolinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image_for_preview', models.ImageField(upload_to='img')),
            ],
        ),
    ]
