# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_infolinks_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infolinks',
            new_name='Infolink',
        ),
    ]
