# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170512_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolink',
            name='image_for_preview',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
