# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 06:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_bigc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigc',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Tramites', 'Tramites'), ('Info', 'Info'), ('Exp', 'Exp')], max_length=256),
        ),
        migrations.AddField(
            model_name='bigc',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bigc',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Nada'),
        ),
    ]
