# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170506_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='categoria',
        ),
    ]
