# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170512_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigc',
            name='image_preview',
            field=models.ImageField(default='static/blog/img/ipad.png', upload_to='img'),
        ),
    ]
