# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170512_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigc',
            name='image_preview',
            field=models.ImageField(default='img/default.png', upload_to='img'),
        ),
    ]
