# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170512_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigc',
            name='note',
            field=models.CharField(default='', help_text='Imagenes deben ser de una resolucion: 600px ancho, 400px de alto. Esto para evitar inconvenientes', max_length=200),
        ),
    ]
